quarkus:
   openshift:
      namespace: appui-backend-project
      route:
         expose: true
      part-of: appui-backend
   kubernetes-client:
      trust-certs: true
   log:
      level: INFO
   swagger-ui:
       always-include: true
   http:
     cors: 
        ~: true
     test-port: 9090

org:
  eclipse:
     microprofile:
        rest:
           client:
               propagateHeaders: TenantKey, Authorization,Proxy-Authorization
               
subject/mp-rest/url: http://appui-course/
course/mp-rest/url: http://appui-course/
tag/mp-rest/url: http://appui-tag/
parent/mp-rest/url: http://appui-student-parent/
student/mp-rest/url: http://appui-student-profile/  
booking/mp-rest/url: http://appui-student-booking/
teacher/mp-rest/url: http://appui-teacher-profile/  
availability/mp-rest/url: http://appui-teacher-availability/  
schedule/mp-rest/url: http://appui-schedule/
comment/mp-rest/url: http://appui-comment/

       