"%test":
  quarkus:
    hibernate-orm:
      database:
         generation: drop-and-create
    kubernetes-config:
      enabled: false
      secrets:
         enabled: false
    datasource:
      db-kind: h2
      username: sa
      password: 
      jdbc:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
          
quarkus:
   openshift:
      namespace: appui-backend-project
      route:
         expose: true
      part-of: appui-backend
   kubernetes-client:
      trust-certs: true
   kubernetes-config:
      enabled: true
      secrets:
         ~: postgres-password
         enabled: true   
   log:
      level: INFO
   swagger-ui:
       always-include: true
   http:
     cors: 
        ~: true
     test-port: 9090
   datasource:
      db-kind: postgresql
      username: appui_scolaire_user
      password: ${postgres-password}
      jdbc:
         max-size: 8
         min-size: 2
         url: jdbc:postgresql://postgresql/availabilities
   hibernate-orm:
      database:
         generation: update
reussite:
    appui:
      activation:
        defaultCodeEnabled: true
      conference:
         enabled: false
         baseUrl: https://bbb1.appui.io/bigbluebutton/api
         authKey: zaFNF1FQLrqpJyVrfNDphPDdBahhPPS7ELksDBH9lM
         url:
           prefix:
             teacher: https://meet.appui.io:3443/
             student: https://meet.appui.io:3443/
             
org:
  eclipse:
     microprofile:
        rest:
           client:
               propagateHeaders: TenantKey, Authorization,Proxy-Authorization
                
schedule/mp-rest/url: http://appui-schedule/
tag/mp-rest/url: http://appui-tag/
booking/mp-rest/url: http://appui-student-booking/
teacher/mp-rest/url: http://appui-teacher-profile/